In [ ]:
Name:Ravipati Bhanu Chandu
700# : 700728966

In [7]:
import statistics
ages=[19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
#Sorting the list
ages.sort()
print(ages)
#Minimum age
min_age=ages[0]
print(min_age)
#Maximum age
max_age=ages[len(ages)-1]
print(max_age)
#Appending minimum and miximum ages to list
ages.append(min_age)
ages.append(max_age)
print(ages)
#Median
median=statistics.median(ages)
print(median)
#Average
length=len(ages)
sum_ages=sum(ages)
average=sum_ages/length
print(average)
#Range 
range=(max_age-min_age)
print(range)


[19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
19
26
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 19, 26]
24.0
22.75
7


In [11]:
#Dog dictionary
dog={}
dog['name']='Kushi'
dog['color']='brown'
dog['breed']='German Shepard'
dog['legs']='brown'
dog['age']='2'
print(dog)
#Student dictonary
student={}
student['first_name']='Bhanu Chandu'
student['last_name']='Ravipati'
student['gender']='Male'
student['age']='23'
student['marital status']='Single'
student['Skills']=['Python','aws']
student['country']='USA'
student['city']='Overland Park'
student['address']='14000 floyd street'
print(student)
#length of the dictonary
print(len(student))
#value of the skill and checking datatype
print(type(student['Skills']))
#Modifing Skills  
student['Skills']=['Python','aws','Java','C#']
print(student)
#Getting Keys as list
keys=student.keys()
print(list(keys))
#Getting values as list
values=student.values()
print(list(values))

{'name': 'Kushi', 'color': 'brown', 'breed': 'German Shepard', 'legs': 'brown', 'age': '2'}
{'first_name': 'Bhanu Chandu', 'last_name': 'Ravipati', 'gender': 'Male', 'age': '23', 'marital status': 'Single', 'Skills': ['Python', 'aws'], 'country': 'USA', 'city': 'Overland Park', 'address': '14000 floyd street'}
9
<class 'list'>
{'first_name': 'Bhanu Chandu', 'last_name': 'Ravipati', 'gender': 'Male', 'age': '23', 'marital status': 'Single', 'Skills': ['Python', 'aws', 'Java', 'C#'], 'country': 'USA', 'city': 'Overland Park', 'address': '14000 floyd street'}
['first_name', 'last_name', 'gender', 'age', 'marital status', 'Skills', 'country', 'city', 'address']
['Bhanu Chandu', 'Ravipati', 'Male', '23', 'Single', ['Python', 'aws', 'Java', 'C#'], 'USA', 'Overland Park', '14000 floyd street']


In [10]:
brothers_tuple=('Teja','Kotu')
sisters_tuple=('jyoshna','vishnu')
#Joining brothers tuple and sisters tuple
siblings=brothers_tuple+sisters_tuple
print(siblings)
#Length of the siblings
print(len(siblings))
#Modifing siblings tuple and adding parents to it
siblings=list(siblings)
siblings.append('venkata rao')
siblings.append('sujatha')
#Family members tuple
family_members=tuple(siblings)
family_members

('Teja', 'Kotu', 'jyoshna', 'vishnu')
4


('Teja', 'Kotu', 'jyoshna', 'vishnu', 'venkata rao', 'sujatha')

In [8]:
it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
age = [22, 19, 24, 25, 26, 24, 25, 24]
#Find the length of the set it_companies
print(len(it_companies))
# Add 'Twitter' to it_companies
it_companies.add('Twitter')
print(it_companies)
#Insert multiple IT companies at once to the set it_companies
new_companies=['Valuelabs','CTS','Infosys']
it_companies.update(new_companies)
print(it_companies)
#Remove one of the companies from the set it_companies
it_companies.remove('CTS')
print(it_companies)
#Difference between remove and discard
'''
remove() method will remove the specific elemet from the set. If the element is not present it will raise an error
dicard() methos will works same as remove() but it wont raise any error even the element is not present
'''
#Example for discard
it_companies.discard('CTS')
print(it_companies)
#Join A and B
C=A.union(B)
print(C)
#Find A intersection B
D=A.intersection(B)
print(D)
#Is A subset of B
print(A.issubset(B))
#Are A and B disjoint sets
print(A.isdisjoint(B))
#Join A with B and B with A
print(A.union(B))
print(B.union(A))
#What is the symmetric difference between A and B
print(A.symmetric_difference(B))
#Delete the sets completely
del it_companies
del A
del B
#Convert the ages to a set and compare the length of the list and the set
print(len(age))
age_set=set(age)
print(len(age_set))



7
{'IBM', 'Amazon', 'Microsoft', 'Google', 'Apple', 'Oracle', 'Twitter', 'Facebook'}
{'Microsoft', 'IBM', 'Google', 'Apple', 'CTS', 'Infosys', 'Amazon', 'Valuelabs', 'Oracle', 'Twitter', 'Facebook'}
{'Microsoft', 'IBM', 'Google', 'Apple', 'Infosys', 'Amazon', 'Valuelabs', 'Oracle', 'Twitter', 'Facebook'}
{'Microsoft', 'IBM', 'Google', 'Apple', 'Infosys', 'Amazon', 'Valuelabs', 'Oracle', 'Twitter', 'Facebook'}
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26}
True
False
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26, 27, 28}
{27, 28}
8
5


In [9]:
radius=30
_area_of_circle_=(3.14)*(radius)*(radius)
print(_area_of_circle_)
_circum_of_circle_=(2)*(3.14)*(radius)
print(_circum_of_circle_)
user_radius=int(input("Enter the value of radius"))
print((3.14)*(user_radius)*(user_radius))

2826.0
188.4
Enter the value of radius10
314.0


In [10]:
sen='I am a teacher and I love to inspire and teach people'
#Splitting the word with space
word_count=sen.split(" ")
#Getting unique words using set
unique_word=set(word_count)
print(unique_word)
#Length of the set
print(len(unique_word))

{'to', 'and', 'inspire', 'teach', 'I', 'love', 'am', 'teacher', 'people', 'a'}
10


In [11]:
print("Name\t\tAge\tCountry\tCity\nAsabeneh\t250\tFinland\tHelsinki")

Name		Age	Country	City
Asabeneh	250	Finland	Helsinki


In [18]:
print("radius = {radius}".format(radius=10))
print("area = {PI}*radius**2".format(PI=3.14))
print("\"The area of a circle with radius {radius} is {area} meters square""\"".format(radius=10,area=(3.14)*(radius)*(radius)))

radius = 10
area = 3.14*radius**2
"The area of a circle with radius 10 is 314.0 meters square"


In [12]:
weights_in_Lbs=[int(x) for x in input().split(',')]
weights_in_Kgs=[]
for i in weights_in_Lbs:
    kgdata= i/2.205
    weights_in_Kgs.append(round(kgdata,2))
print(weights_in_Kgs)

150,155,145,148
[68.03, 70.29, 65.76, 67.12]


In [4]:
import numpy as np
from sklearn.model_selection import train_test_split
#Importing for implementing knn
from sklearn.neighbors import KNeighborsClassifier
#Splitting data into training and testing data
data1=np.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]])
data2=np.array([0,0,1,1,1,0,0,0])
data1_train,data1_test,data2_train,data2_test=train_test_split(data1,data2,test_size=0.5,random_state=0,shuffle=False)
print(data1_train)
print(data2_train)
#implementing knn with 3
n=KNeighborsClassifier(n_neighbors=3)
#fitting the knn from the training data
n.fit(x_train,y_train)
data2_pred=n.predict(data1_test)
print(data2_pred)

[[1 0]
 [2 0]
 [3 0]
 [6 0]]
[0 0 1 1]
[1 1 1 1]


In [6]:
from sklearn.metrics import confusion_matrix
#comparing test class labels with predicted class lables
(confusion_matrix(data2_test,data2_pred))

array([[0, 3],
       [0, 1]], dtype=int64)